// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrteaoncoflxevnxwyze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydGVhb25jb2ZseGV2bnh3eXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwODUxNTUsImV4cCI6MjA3NTY2MTE1NX0.LUHdAebzILPZl-hHf_NqsXyBY4fCPfdpCDoiLH94-CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});